public class Constants {
	public static final Integer APPOINTMENT_TIME_IN_MINUTES = 30;
	public static final Integer EARLIEST_POSSIBLE_APPOINTMENT_DAYS = 1;
	public static final Integer LAST_POSSIBLE_APPOINTMENT_DAYS = 400;
	public static final String CLINIC_TIMEZONE = 'Europe/Berlin';

	public static final String APPOINTMENT_STATUS_TEMPORARY = 'Temporary';
	public static final String APPOINTMENT_STATUS_AWAITING = 'Awaiting confirmation';
	public static final String APPOINTMENT_STATUS_CONFIRMED = 'Confirmed';
	public static final String APPOINTMENT_STATUS_REJECTED = 'Rejected';

	public static final String AVAILABLE_TIME_MESSAGE_OVERLAP = 'There is another entry for this day that overlaps with the current one.';

	public static final String PROFILE_NAME_OWNER = 'Clinic owner';
	public static final String PROFILE_NAME_DENTIST = 'Dentist';
}